name: Build

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      build-cache-key:
        description: "Cache key for build output"
        value: ${{ jobs.build.outputs.build-cache-key }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-cache-key: ${{ steps.cache-build-output.outputs.cache-hit }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Build
        run: pnpm build

      - name: Cache build output
        id: cache-build-output
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-output-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-output-

