name: "Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
		  
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Checkout oscd-plugins/main
        uses: actions/checkout@v4

      - name: Build
        run: pnpm build

      - name: Retrieve Version
        id: version
        run: echo "version=$(npm pkg get version)" >> "$GITHUB_OUTPUT"

      - name: Publish
        run: echo "TODO"