name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install Dependencies
    uses: ./.github/workflows/_install.yml

  build:
    name: Build Project
    needs: install
    uses: ./.github/workflows/_build.yml

  test:
    name: Run Tests
    needs: install
    uses: ./.github/workflows/_test.yml