name: Pull Request Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install Dependencies
    uses: ./.github/workflows/install.yml

  build:
    name: Build Project
    needs: install
    uses: ./.github/workflows/build.yml

  test:
    name: Run Tests
    needs: install
    uses: ./.github/workflows/test.yml